### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by diegorubert** [beingmrkenny/HideActivityForTrello#1]
Hi,
Today I opened Trello and the hashtag #done (for instance) doesn't make the list transparent anymore...
Let me know if I can help.

Firefox 119.0
Extension 4.0.11

  Diego

**Comment by beingmrkenny** [comment]
Hi, Trello made some changes that have made a number of extensions stop working. I'm working on a fix that should be out soon.

Thanks,

Mark

**Comment by diegorubert** [comment]
That's great, thanks!

Em sex., 20 de out. de 2023 às 08:46, Mark Kenny ***@***.***>
escreveu:
